// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc303EA3_R5dblhNa332Wy-Ld41vF6v2c',
    appId: '1:18688200948:web:0a42d28730a6789e080ea1',
    messagingSenderId: '18688200948',
    projectId: 'chillihub-3359c',
    authDomain: 'chillihub-3359c.firebaseapp.com',
    databaseURL: 'https://chillihub-3359c-default-rtdb.firebaseio.com',
    storageBucket: 'chillihub-3359c.firebasestorage.app',
    measurementId: 'G-78E5EDJ28N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN6tSUe-BlEYop_mzjRZfjS5PNVQzVXFA',
    appId: '1:18688200948:android:f6ee09f985b7b3d2080ea1',
    messagingSenderId: '18688200948',
    projectId: 'chillihub-3359c',
    databaseURL: 'https://chillihub-3359c-default-rtdb.firebaseio.com',
    storageBucket: 'chillihub-3359c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDncFqOI9B1wL7HlwRrZI7pdXA-qyNVOAU',
    appId: '1:18688200948:ios:ee1f7bf1a5c9ce03080ea1',
    messagingSenderId: '18688200948',
    projectId: 'chillihub-3359c',
    databaseURL: 'https://chillihub-3359c-default-rtdb.firebaseio.com',
    storageBucket: 'chillihub-3359c.firebasestorage.app',
    androidClientId: '18688200948-9l8l7rmgsuek1vt8gkdl18m4684bbtf5.apps.googleusercontent.com',
    iosClientId: '18688200948-q4o5eftrf20v2mpikkqlnb0l16c90gaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.translate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDncFqOI9B1wL7HlwRrZI7pdXA-qyNVOAU',
    appId: '1:18688200948:ios:ee1f7bf1a5c9ce03080ea1',
    messagingSenderId: '18688200948',
    projectId: 'chillihub-3359c',
    databaseURL: 'https://chillihub-3359c-default-rtdb.firebaseio.com',
    storageBucket: 'chillihub-3359c.firebasestorage.app',
    androidClientId: '18688200948-9l8l7rmgsuek1vt8gkdl18m4684bbtf5.apps.googleusercontent.com',
    iosClientId: '18688200948-q4o5eftrf20v2mpikkqlnb0l16c90gaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.translate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc303EA3_R5dblhNa332Wy-Ld41vF6v2c',
    appId: '1:18688200948:web:72cdd1b7ebbbf789080ea1',
    messagingSenderId: '18688200948',
    projectId: 'chillihub-3359c',
    authDomain: 'chillihub-3359c.firebaseapp.com',
    databaseURL: 'https://chillihub-3359c-default-rtdb.firebaseio.com',
    storageBucket: 'chillihub-3359c.firebasestorage.app',
    measurementId: 'G-JDKD5ZWD01',
  );
}
